  <section>
        <form action = "createAdmin.php" method="post">
            <fieldset>
                <legend>Create new Account</legend>
                <p>
                    <label for="pseudo">Pseudo : </label>
                    <input type="text" name="pseudo"/>
                </p>
                 <p>
                    <label for="password">Password : </label>
                    <input type="password" name="password"/>
                </p>
                <p class="buttons">
                    <input type="submit" name="create" value="Create New Account"/>
                </p>
            </fieldset>
        </form>
</section>