<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Layout</title>
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  
    
    <link href="https://fonts.googleapis.com/css2?family=Merienda:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400;1,500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="./css/normalize.css" type="text/css" />
    <link rel="stylesheet" href="./css/style.css" type="text/css" />
    
      <script src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <h1><i class="fa-solid fa-microphone-lines"></i>Encore un blog ?! #nonmaisallo</h1>
        <nav>
            <ul>
                <li><a href="./index.php"><i class="fas fa-home"></i> Acceuil</a></li>
                <li><a href="./login.php"><i class="fas fa-user-lock"></i> Administrator</a></li>
            </ul>
        </nav>
    </header>

    <?php require $template.".phtml"; ?> 
    
    <footer>
        <section>
            <h3>Contact info</h3>

            <ul>
                <li><a href="tel: 0712345678"><i class="fas fa-phone"></i></a></li>
                <li><a href=""><i class="fab fa-facebook"></i></a></li>
                <li><a href=""><i class="fab fa-instagram"></i></a></li>
                <li><a href=""><i class="fab fa-twitter"></i></a></li>
            </ul>

        </section>
    </footer>
</body>
</html>


