<?php
  
 if(isset($_SESSION['Admins'])) :?>


    <main>
         <h3>Edit an Article</h3>
        <p><a href="./admin.php">Go back</a></p>
        
        <form action="update.php" method="post" enctype="multipart/form-data">
            <fieldset>
                   <legend>Update your Article</legend>
                   <p>
                      <input type="hidden" name="id_Number" value="<?= $id_Number ?>"/>
                       <label for="titre" >Title : </label>
                       <input type="text" name="titre" value="<?= $edited["title"];?>"/>
                   </p>
                   <p>
                        <label for="article">Article : </label>
                       <input type="textarea" name="article" class="form_article" value="<?= $edited["content"];?>"/>
                   </p>
                   <p>
                       <p>
                         <img src="./uploads/<?= $edited["image"]?>" alt="<?= $edited["title"]?>"></img>
                        </p>
                       <label for="images">Insert new image</label>
                       <input type="file" name="images">
                   </p>
                    <p>
                        <label for="actor">Choose an Actor</label>
                            <select name="actor" id="actor">
                                 <?php foreach($actors as $value): ?>
                                     <option value="<?= $value["id_Number"] ?>"><?= $value["first_Name"]." ".$value["last_Name"] ?></option>
                                 <?php endforeach ;?>
                            </select>
                          
                   </p>
                    <p>
                      <label for="category">Choose a Category</label>
                            
                            <select name="category" id="category">
                                <?php foreach($categories as $value): ?>
                                    <option value="<?=  $value["id_Number"]?>"><?= $value["category"] ?></option>
                                <?php endforeach ;?>
                            </select>
                 
                   </p>
                    <p class="buttons">
                       <input type="submit" name="update" value="update"/>
                   </p>
               </fieldset>
            
        </form>
        
    </main>


<?php else: ?>

    <?= header("location:login.php");  
            exit(); ?>
 

<?php endif; ?>
